```{r library, include = FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(tidymodels)
library(patchwork)
data <- read_excel("DataForTable2.1.xls")
continent <- read.csv("countryContinent.csv")
```

```{r tidy data}
data <- clean_names(data)

# filter the data of the countries with both 2011 and 2021
data_2011 <- data %>%
  clean_names() %>% 
  select(country_name, year, life_ladder, social_support, healthy_life_expectancy_at_birth) %>%
  filter(year == "2011")

data_2021 <- data %>%
  clean_names() %>% 
  select(country_name, year, life_ladder, social_support, healthy_life_expectancy_at_birth) %>%
  filter(year == "2021")
  
data_cleaned <- inner_join(data_2011, data_2021, by = "country_name") %>%
  summarise(country = country_name, 
            year_2011 = year.x,
            life_ladder_2011 = life_ladder.x,
            social_support_2011 = social_support.x,
            life_expectancy_2011 = healthy_life_expectancy_at_birth.x,
            year_2021 = year.y,
            life_ladder_2021 = life_ladder.y,
            social_support_2021 = social_support.y,
            life_expectancy_2021 = healthy_life_expectancy_at_birth.y) %>%
  #filter the data without NAs in both the two variables
  filter(!is.na(life_expectancy_2011))
```

```{r merge}
# merge the data and change the country names to aviod NAs
continents <- continent %>%
  select(country, continent) %>%
  mutate(country = if_else(country == "Bolivia (Plurinational State of)", "Bolivia", country),
         country = if_else(country == "Congo", "Congo (Brazzaville)", country),
         country = if_else(country == "Czech Republic", "Czechia", country),
         country = if_else(country == "Iran (Islamic Republic of)", "Iran", country),
         country = if_else(country == "Lao People's Democratic Republic", "Laos", country),
         country = if_else(country == "Moldova (Republic of)", "Moldova", country),
         country = if_else(country == "Macedonia (the former Yugoslav Republic of)", "North Macedonia", country),
         country = if_else(country == "Russian Federation", "Russia", country),
         country = if_else(country == "Korea (Republic of)", "South Korea", country),
         country = if_else(country == "Tanzania, United Republic of", "Tanzania", country),
         country = if_else(country == "United Kingdom of Great Britain and Northern Ireland", "United Kingdom", country),
          country = if_else(country == "United States of America", "United States", country),
          country = if_else(country == "Venezuela (Bolivarian Republic of)", "Venezuela", country),
          country = if_else(country == "Viet Nam", "Vietnam", country)
        )

data_by_continent <- left_join(data_cleaned, continents, by = "country")
```

```{r America}
data_by_continent %>%
  filter(continent == "Americas") %>%
  ggplot(aes(x = life_expectancy_2011, y = life_ladder_2011)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) 

americas_life_expec_fit_2011 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2011 ~ life_expectancy_2011, data = (filter(data_by_continent, continent == "Americas")))

tidy(americas_life_expec_fit_2011)

#life_ladder_2011-hat = -8.6874841 + 0.2259208*life_expectancy_2011

glance(americas_life_expec_fit_2011)$r.squared

#r^2 = 0.389

data_by_continent %>%
 filter(continent == "Americas") %>%
  ggplot(aes(x = life_expectancy_2021, y = life_ladder_2021)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) 
  
americas_life_expec_fit_2021 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2021 ~ life_expectancy_2021, data = (filter(data_by_continent, continent == "Americas")))

tidy(americas_life_expec_fit_2021)

#life_ladder_2021-hat = 1.82149917 + 0.06298284	*life_expectancy_2021

glance(americas_life_expec_fit_2021)$r.squared

#r^2 = 0.085
```

```{r EU}
data_by_continent %>%
  filter(continent == "Europe") %>%
  ggplot(aes(x = life_expectancy_2011, y = life_ladder_2011)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) 

europe_life_expec_fit_2011 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2011 ~ life_expectancy_2011, data = (filter(data_by_continent, continent == "Europe")))

tidy(europe_life_expec_fit_2011)

#life_ladder_2011-hat = -9.0345375 + 0.2211496*life_expectancy_2011

glance(europe_life_expec_fit_2011)$r.squared

#r^2 = 0.4399011

data_by_continent %>%
 filter(continent == "Europe") %>%
  ggplot(aes(x = life_expectancy_2021, y = life_ladder_2021)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) 
  
europe_life_expec_fit_2021 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2021 ~ life_expectancy_2021, data = (filter(data_by_continent, continent == "Europe")))

tidy(europe_life_expec_fit_2021)

#life_ladder_2021-hat = -5.9762152 + 0.1791352	*life_expectancy_2021

glance(europe_life_expec_fit_2021)$r.squared

#r^2 = 0.4247694
```

```{r Africa}
data_by_continent %>%
  filter(continent == "Africa") %>%
  ggplot(aes(x = life_expectancy_2011, y = life_ladder_2011)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

africa_life_expec_fit_2011 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2011 ~ life_expectancy_2011, data = (filter(data_by_continent, continent == "Africa")))

tidy(africa_life_expec_fit_2011)

#life_ladder_2011-hat = 3.112 + 0.027*life_expectancy_2011

glance(africa_life_expec_fit_2011)$r.squared

#R2 = 0.06255119

data_by_continent %>%
  filter(continent == "Africa") %>%
  ggplot(aes(x = life_expectancy_2021, y = life_ladder_2021)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

africa_life_expec_fit_2021 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2021 ~ life_expectancy_2021, data = (filter(data_by_continent, continent == "Africa")))
  
tidy(africa_life_expec_fit_2021)

#life_ladder_2021-hat = 1.332 + 0.054*life_expectancy_2021

glance(africa_life_expec_fit_2021)$r.squared

#R2 = 0.08868883
```

```{r Asia}
data_by_continent %>%
  filter(
    continent == "Asia"
  ) %>%
  ggplot(aes(x = life_expectancy_2021, y = life_ladder_2021)) +
  geom_point() +
  labs(x = "Healthy Life Expectancy",
       y = "Life Ladder",
       title = "Asia") +
  geom_smooth(
    formula = y ~ x,
    method = lm
  ) +
  ggpubr::stat_regline_equation(
    formula = y ~ x,
    show.legend = FALSE
  )
# LL vs LE, slope = 0.13

data_by_continent %>%
  filter(
    continent == "Asia"
  ) %>%
  ggplot(aes(x = social_support_2021, y = life_ladder_2021)) +
  geom_point() +
  labs(x = "Social Support",
       y = "Life Ladder",
       title = "Asia") +
  geom_smooth(
    formula = y ~ x,
    method = lm
  ) +
  ggpubr::stat_regline_equation(
    formula = y ~ x,
    show.legend = FALSE
  )
# LL vs SS, slope = 8.3

```

```{r life expectancy fit lm}
life_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2021 ~ life_expectancy_2021 + continent, data = data_by_continent)
tidy(life_fit)
```
```{r means}
mean_var_asia <- data_by_continent %>%
  filter(continent == "Asia")%>%
  summarise(
    mean_life_ladder = mean(life_ladder_2021),
    mean_life_exp = mean(life_expectancy_2021),
    mean_social = mean(social_support_2021))

mean_var_america <- data_by_continent %>%
  filter(continent == "Americas")%>%
  summarise(
    mean_life_ladder = mean(life_ladder_2021),
    mean_life_exp = mean(life_expectancy_2021),
    mean_social = mean(social_support_2021))

mean_var_eu <- data_by_continent %>%
  filter(continent == "Europe")%>%
  summarise(
    mean_life_ladder = mean(life_ladder_2021),
    mean_life_exp = mean(life_expectancy_2021),
    mean_social = mean(social_support_2021))

mean_var_africa <- data_by_continent %>%
  filter(continent == "Africa")%>%
  summarise(
    mean_life_ladder = mean(life_ladder_2021),
    mean_life_exp = mean(life_expectancy_2021),
    mean_social = mean(social_support_2021))

# we can run a t test (two tail, non-paired) to see if Asian countries' healthy life expectancy or something is significantly different form the others
```

```{r social support fit lm}
social_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(life_ladder_2021 ~ social_support_2021 + continent, data = data_by_continent)
tidy(social_fit)
```

```{r general 2021}

```

```{r general 2011}

```

